title:              Khanh Nguyen's Blog
email:              khanh1895@gmail.com
description:        Just another PM on the internet
author:             Khanh Nguyen
baseurl:            "https://khanhng1895.github.io"
url:                ""

# Social Profiles
twitter_username:
github_username:
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
